const questions = [
  {
    prompt: "What is budgeting?",
    options: ["Tracking only income", "Planning income and expenses", "Avoiding taxes", "Investing in stocks"],
    correctIndex: 1,
    category: "Basics",
    difficulty: "Easy",
  },
  {
    prompt: "Which is an asset?",
    options: ["Loan", "Credit card bill", "Savings account balance", "Electricity dues"],
    correctIndex: 2,
    category: "Basics",
    difficulty: "Easy",
  },
  {
    prompt: "What does EMI stand for?",
    options: ["Equal Monthly Installment", "Easy Money Income", "Electronic Market Index", "Expense Managed Income"],
    correctIndex: 0,
    category: "Basics",
    difficulty: "Easy",
  },
  {
    prompt: "Simple interest depends on?",
    options: ["Principal", "Rate", "Time", "All of the above"],
    correctIndex: 3,
    category: "Basics",
    difficulty: "Easy",
  },
  {
    prompt: "Compound interest means?",
    options: ["Interest on principal only", "Interest on interest", "Fixed tax", "Loan penalty"],
    correctIndex: 1,
    category: "Basics",
    difficulty: "Easy",
  },
  {
    prompt: "A credit score represents?",
    options: ["Your salary", "Loan eligibility and repayment history", "Bank balance", "Tax paid"],
    correctIndex: 1,
    category: "Basics",
    difficulty: "Easy",
  },
  {
    prompt: "Inflation means?",
    options: ["Decrease in prices", "Increase in prices", "Stable economy", "Higher interest"],
    correctIndex: 1,
    category: "Economics",
    difficulty: "Easy",
  },
  {
    prompt: "Which is a liability?",
    options: ["House owned", "Car loan", "Investments", "Gold"],
    correctIndex: 1,
    category: "Basics",
    difficulty: "Easy",
  },
  {
    prompt: "SIP is related to?",
    options: ["Insurance", "Mutual funds", "Credit cards", "Taxes"],
    correctIndex: 1,
    category: "Investing",
    difficulty: "Easy",
  },
  {
    prompt: "Diversification helps to?",
    options: ["Increase tax", "Reduce risk", "Stop returns", "Freeze money"],
    correctIndex: 1,
    category: "Investing",
    difficulty: "Easy",
  },
  {
    prompt: "IPO means?",
    options: ["Initial Public Offering", "Internal Price Order", "Investor Purchase Option", "Index Public Operation"],
    correctIndex: 0,
    category: "Markets",
    difficulty: "Easy",
  },
  {
    prompt: "A bull market indicates?",
    options: ["Falling prices", "Rising prices", "No trading", "Panic selling"],
    correctIndex: 1,
    category: "Markets",
    difficulty: "Easy",
  },
  {
    prompt: "Sensex belongs to which exchange?",
    options: ["NSE", "BSE", "RBI", "SEBI"],
    correctIndex: 1,
    category: "Markets",
    difficulty: "Easy",
  },
  {
    prompt: "Dividend is?",
    options: ["Company profit shared with shareholders", "Tax", "Loan", "Brokerage"],
    correctIndex: 0,
    category: "Markets",
    difficulty: "Easy",
  },
  {
    prompt: "Market capitalization = ?",
    options: ["Profit x tax", "Share price x total shares", "Revenue - expense", "Assets - liability"],
    correctIndex: 1,
    category: "Markets",
    difficulty: "Easy",
  },
  {
    prompt: "Blue chip companies are?",
    options: ["New startups", "Fraud companies", "Well-established stable firms", "Penny stocks"],
    correctIndex: 2,
    category: "Markets",
    difficulty: "Easy",
  },
  {
    prompt: "Nifty is associated with?",
    options: ["NSE", "BSE", "RBI", "LIC"],
    correctIndex: 0,
    category: "Markets",
    difficulty: "Easy",
  },
  {
    prompt: "A trader who expects price fall is called?",
    options: ["Bull", "Bear", "Broker", "Investor"],
    correctIndex: 1,
    category: "Markets",
    difficulty: "Easy",
  },
  {
    prompt: "Equity means?",
    options: ["Loan", "Ownership in company", "Bond", "Deposit"],
    correctIndex: 1,
    category: "Markets",
    difficulty: "Easy",
  },
  {
    prompt: "Long term investment usually means?",
    options: ["Few minutes", "Few days", "Several years", "One hour"],
    correctIndex: 2,
    category: "Investing",
    difficulty: "Easy",
  },
  {
    prompt: "RBI stands for?",
    options: ["Reserve Bank of India", "Royal Bank of India", "Rural Bank Institute", "Revenue Bureau India"],
    correctIndex: 0,
    category: "Banking",
    difficulty: "Easy",
  },
  {
    prompt: "Fixed deposit offers?",
    options: ["Variable return", "Guaranteed return", "No return", "Equity ownership"],
    correctIndex: 1,
    category: "Banking",
    difficulty: "Easy",
  },
  {
    prompt: "NEFT is used for?",
    options: ["Cash withdrawal", "Online fund transfer", "Loan approval", "Credit score check"],
    correctIndex: 1,
    category: "Banking",
    difficulty: "Easy",
  },
  {
    prompt: "ATM allows?",
    options: ["Only deposits", "Only balance check", "Banking transactions without visiting branch", "Opening FD"],
    correctIndex: 2,
    category: "Banking",
    difficulty: "Easy",
  },
  {
    prompt: "KYC means?",
    options: ["Keep Your Cash", "Know Your Customer", "Key Yield Control", "Keep Your Credit"],
    correctIndex: 1,
    category: "Banking",
    difficulty: "Easy",
  },
  {
    prompt: "Interest given by bank on savings is called?",
    options: ["Deposit return", "Savings interest", "Dividend", "Bonus"],
    correctIndex: 1,
    category: "Banking",
    difficulty: "Easy",
  },
  {
    prompt: "A cheque bounce happens due to?",
    options: ["Extra money", "Signature style", "Insufficient balance", "RBI order"],
    correctIndex: 2,
    category: "Banking",
    difficulty: "Easy",
  },
  {
    prompt: "Net banking requires?",
    options: ["Passbook", "Internet access", "Visiting branch", "Cheque"],
    correctIndex: 1,
    category: "Banking",
    difficulty: "Easy",
  },
  {
    prompt: "A debit card deducts money from?",
    options: ["Bank account", "Credit line", "RBI", "Fixed deposit"],
    correctIndex: 0,
    category: "Banking",
    difficulty: "Easy",
  },
  {
    prompt: "A credit card allows?",
    options: ["Using your own savings", "Borrowing money to pay later", "Investing", "Tax payment only"],
    correctIndex: 1,
    category: "Banking",
    difficulty: "Easy",
  },
  {
    prompt: "Emergency fund should cover roughly?",
    options: ["1 week expense", "1 month expense", "3-6 months expense", "10 years expense"],
    correctIndex: 2,
    category: "Personal Finance",
    difficulty: "Easy",
  },
  {
    prompt: "Higher return usually means?",
    options: ["Lower risk", "Higher risk", "No risk", "Guaranteed profit"],
    correctIndex: 1,
    category: "Personal Finance",
    difficulty: "Easy",
  },
  {
    prompt: "PPF is mainly for?",
    options: ["Shopping", "Long-term savings and tax benefit", "Daily expenses", "Trading"],
    correctIndex: 1,
    category: "Investing",
    difficulty: "Easy",
  },
  {
    prompt: "Mutual funds are managed by?",
    options: ["Government", "Investors", "Professional fund managers", "Banks only"],
    correctIndex: 2,
    category: "Investing",
    difficulty: "Easy",
  },
  {
    prompt: "Liquidity means your asset can be?",
    options: ["Locked", "Sold quickly", "Taxed", "Insured"],
    correctIndex: 1,
    category: "Personal Finance",
    difficulty: "Easy",
  },
  {
    prompt: "Insurance protects against?",
    options: ["Profits", "Future uncertainties", "Inflation", "Investments"],
    correctIndex: 1,
    category: "Personal Finance",
    difficulty: "Easy",
  },
  {
    prompt: "Term insurance mainly covers?",
    options: ["Vehicle", "Life risk", "Property", "Travel"],
    correctIndex: 1,
    category: "Personal Finance",
    difficulty: "Easy",
  },
  {
    prompt: "A bond is basically?",
    options: ["Ownership", "Loan given to issuer", "Share market", "Insurance"],
    correctIndex: 1,
    category: "Investing",
    difficulty: "Easy",
  },
  {
    prompt: "Real estate is considered?",
    options: ["Expense", "Liability", "Asset", "Tax"],
    correctIndex: 2,
    category: "Personal Finance",
    difficulty: "Easy",
  },
  {
    prompt: "Retirement planning helps to?",
    options: ["Spend more now", "Secure future income", "Avoid bank", "Increase EMI"],
    correctIndex: 1,
    category: "Personal Finance",
    difficulty: "Easy",
  },
  {
    prompt: "GDP measures?",
    options: ["Population", "Total value of goods and services", "Inflation", "Tax"],
    correctIndex: 1,
    category: "Economics",
    difficulty: "Easy",
  },
  {
    prompt: "Repo rate is decided by?",
    options: ["SEBI", "RBI", "Banks", "Government employees"],
    correctIndex: 1,
    category: "Economics",
    difficulty: "Easy",
  },
  {
    prompt: "When repo rate increases, loans become?",
    options: ["Cheaper", "Costlier", "Free", "Cancelled"],
    correctIndex: 1,
    category: "Economics",
    difficulty: "Easy",
  },
  {
    prompt: "Tax is collected by?",
    options: ["Companies", "Government", "RBI", "Stock market"],
    correctIndex: 1,
    category: "Economics",
    difficulty: "Easy",
  },
  {
    prompt: "Fiscal deficit happens when?",
    options: ["Income > expense", "Expense > income", "Both equal", "No tax"],
    correctIndex: 1,
    category: "Economics",
    difficulty: "Easy",
  },
  {
    prompt: "Supply more than demand usually leads to?",
    options: ["Price rise", "Price fall", "Stable price", "Market crash"],
    correctIndex: 1,
    category: "Economics",
    difficulty: "Easy",
  },
  {
    prompt: "Currency depreciation makes imports?",
    options: ["Cheaper", "Costlier", "Free", "Illegal"],
    correctIndex: 1,
    category: "Economics",
    difficulty: "Easy",
  },
  {
    prompt: "Subsidy is?",
    options: ["Extra tax", "Government financial support", "Bank charge", "Investment"],
    correctIndex: 1,
    category: "Economics",
    difficulty: "Easy",
  },
  {
    prompt: "Break-even means?",
    options: ["Profit", "No profit, no loss", "Heavy loss", "Double income"],
    correctIndex: 1,
    category: "Basics",
    difficulty: "Easy",
  },
  {
    prompt: "Net worth = ?",
    options: ["Income - tax", "Assets - liabilities", "Profit - expense", "Investment x time"],
    correctIndex: 1,
    category: "Basics",
    difficulty: "Easy",
  }
];

module.exports = { questions };
